name: openra_launcher
description: A desktop application for launching OpenRA mods.
publish_to: "none"
version: 1.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  build_runner: ^2.2.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  file: ^6.1.4
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  mockito: ^5.3.0
  package_info_plus: ^3.0.3
  path: ^1.8.1
  path_provider: ^2.0.9
  platform: ^3.1.0
  process: ^4.2.4
  provider: ^6.0.2
  redux: ^5.0.0
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4
  xdg_directories: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
